#1. Monthly Meeting Room Revenue in 2023
SELECT 
    DATE_FORMAT(reservation.checkInDate, '%Y-%m') AS Month,
    SUM(sleeping_room.sleepingRoomRate * DATEDIFF(reservation.checkOutDate, reservation.checkInDate)) AS Total_Revenue
FROM 
    reservation
JOIN 
    sleeping_room ON reservation.roomId = sleeping_room.sleepingRoomId
WHERE 
    YEAR(reservation.checkInDate) = 2023
    AND reservation.roomId LIKE 'SR%'
GROUP BY 
    DATE_FORMAT(reservation.checkInDate, '%Y-%m')
ORDER BY 
    Month;
#his query provides insights into seasonal demand for meeting rooms, helping management plan pricing strategies and promotional efforts during high-demand months.

#2 Reservation counts Per Month in 2023
SELECT 
    DATE_FORMAT(reservation.checkInDate, '%Y-%m') AS Month,
    COUNT(*) AS Total_Reservations
FROM 
    reservation
WHERE 
    YEAR(reservation.checkInDate) = 2023
GROUP BY 
    DATE_FORMAT(reservation.checkInDate, '%Y-%m')
ORDER BY 
    Month;
#Tracking monthly reservation trends aids in identifying peak periods and potential low-occupancy months, enabling better resource allocation and marketing efforts.
    
# 3. Which sleeping room is the most popular choice (room_rate)? 
SELECT 
    sleeping_room.sleepingRoomRate AS Room_Rate,
    COUNT(*) AS Reservation_Count
FROM 
    reservation
JOIN 
    sleeping_room ON reservation.roomId = sleeping_room.sleepingRoomId
WHERE 
    reservation.roomId LIKE 'SR%' 
GROUP BY 
    sleeping_room.sleepingRoomRate
ORDER BY 
    Reservation_Count DESC;
#Understanding which room rate is most frequently booked helps refine pricing strategies and align with customer preferences.
    
#4. Which hotel services were used most frequently?
SELECT 
    service.type AS Service_Type,
    COUNT(*) AS Usage_Count
FROM 
    service
GROUP BY 
    service.type
ORDER BY 
    Usage_Count DESC;
#Identifying the most popular services allows the hotel to prioritize resource allocation and potentially enhance or market these offerings further.


#5. Payment methods by customer
SELECT 
    billing.paymentMethod AS Payment_Method,
    COUNT(*) AS Usage_Count
FROM 
    billing
GROUP BY 
    billing.paymentMethod
ORDER BY 
    Usage_Count DESC;
#Knowing the preferred payment methods helps streamline operations and improve customer satisfaction by focusing on the most widely used payment options.

#6. Total number of Reservations per customer (TOP5)
SELECT 
    guest.guestName AS Guest_Name,
    COUNT(reservation.reservationId) AS Total_Reservations
FROM 
    guest
JOIN 
    reservation ON guest.guestId = reservation.bookerId
GROUP BY 
    guest.guestId
ORDER BY 
    Total_Reservations DESC
LIMIT 5;
#Identifying loyal customers allows management to target them with personalized offers or loyalty programs, boosting retention and revenue.


#7. Comparison of total revenue between sleeping room and meeting room
SELECT 
    combined_room.roomType AS Room_Type,
    SUM(CASE 
        WHEN combined_room.roomType = 'sleeping' THEN sleeping_room.sleepingRoomRate * DATEDIFF(reservation.checkOutDate, reservation.checkInDate)
        WHEN combined_room.roomType = 'meeting' THEN meeting_room.meetingRoomRate * DATEDIFF(reservation.checkOutDate, reservation.checkInDate)
    END) AS Total_Revenue
FROM 
    reservation
JOIN 
    combined_room ON reservation.roomId = combined_room.roomId
LEFT JOIN 
    sleeping_room ON reservation.roomId = sleeping_room.sleepingRoomId
LEFT JOIN 
    meeting_room ON reservation.roomId = meeting_room.meetingRoomId
GROUP BY 
    combined_room.roomType
ORDER BY 
    Total_Revenue DESC;
#Comparing revenue generated by sleeping rooms and meeting rooms helps evaluate the profitability of each category and informs decisions on future investments or marketing focus.
    
#8 Revenue contribution by each event
SELECT 
    e.eventId AS EventID,
    e.eventDate AS EventDate,
    SUM(mr.meetingRoomRate) AS TotalRevenue
FROM 
    event e
JOIN 
    meeting_room mr ON e.meetingRoomId = mr.meetingRoomId
GROUP BY 
    e.eventId, e.eventDate
ORDER BY 
    TotalRevenue DESC;
    
#9 Revenue from services used during stays in February
SELECT 
    s.type AS ServiceType,
    SUM(s.charge) AS TotalRevenue
FROM 
    service s
JOIN 
    room_guest rg ON s.associatedRoomId = rg.roomId
WHERE 
    MONTH(rg.moveInDateTime) = 2 OR MONTH(rg.moveOutDateTime) = 2
GROUP BY 
    s.type
ORDER BY 
    TotalRevenue DESC;
#Identifying service revenue trends during specific months helps optimize service offerings and promotional campaigns to maximize off-season earnings.
    
    
#10 Peak checkin times by time slot
SELECT 
    CASE 
        WHEN HOUR(r.checkInDate) BETWEEN 0 AND 5 THEN '0-6am'
        WHEN HOUR(r.checkInDate) BETWEEN 6 AND 11 THEN '6am-12pm'
        WHEN HOUR(r.checkInDate) BETWEEN 12 AND 17 THEN '12-6pm'
        WHEN HOUR(r.checkInDate) BETWEEN 18 AND 23 THEN '6pm-12am'
    END AS TimePeriod,
    COUNT(r.reservationId) AS ReservationCount
FROM 
    reservation r
GROUP BY 
    TimePeriod
ORDER BY 
    ReservationCount DESC;
#Understanding peak check-in times helps optimize staffing levels and improve the guest check-in experience during busy hours.
    
#11 Revenue by smoking vs. non-smoking rooms
SELECT 
    CASE 
        WHEN f.smoke = 1 THEN 'Smoking Room'
        ELSE 'Non-Smoking Room'
    END AS RoomType,
    SUM(r.deposit) AS TotalRevenue
FROM 
    reservation r
JOIN 
    sleeping_room sr ON r.roomId = sr.sleepingRoomId
JOIN 
    floor f ON sr.floorId = f.floorId
GROUP BY 
    f.smoke
ORDER BY 
    TotalRevenue DESC;
#Analyzing revenue contributions from smoking and non-smoking rooms informs room allocation and helps align with guest preferences or regulatory changes.
    
#12 Average length of stay by furnitureDescription
SELECT 
    sr.furnitureDescription AS RoomType,
    AVG(TIMESTAMPDIFF(DAY, r.checkInDate, r.checkOutDate)) AS AverageStayDuration
FROM 
    reservation r
JOIN 
    sleeping_room sr ON r.roomId = sr.sleepingRoomId
GROUP BY 
    sr.furnitureDescription
ORDER BY 
    AverageStayDuration DESC;
#Knowing the average length of stay for different room types allows for better forecasting and tailored pricing strategies, especially for long-term or short-term bookings.